### ISSUE TITLE
в начале добавить шапку с Copyright, license

### ISSUE THREAD

**Issue by Alexey-T** [TeamFND/DiffUtils#8]

**Comment by ahreenah** [comment]
Не трогать LICENSE

**Comment by Artem3213212** [comment]
Саш это не файл а заголовок в коде.

**Comment by Artem3213212** [comment]
и там сейчас трогать нечего его добавить надо

**Comment by Artem3213212** [comment]
Сори не надо оно уже там есть. Да действительно Саш не трогать.
